import { LiveChannel } from '../types';

export const LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'espn-1',
    name: 'ESPN HD Sports',
    category: 'Sports',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidsrc.me/embed/movie?tmdb=550988', // Embedded preview stream
    currentProgram: 'Live Premier League & NBA Studio Analysis',
    country: 'US / Global',
    isLive: true,
  },
  {
    id: 'sky-sports-main',
    name: 'Sky Sports Football',
    category: 'Sports',
    logo: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidlink.pro/movie/550988',
    currentProgram: 'UEFA Champions League Live Coverage',
    country: 'UK',
    isLive: true,
  },
  {
    id: 'bbc-news',
    name: 'BBC News 24/7',
    category: 'News',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidsrc.to/embed/movie/550988',
    currentProgram: 'Global World Headlines & Live Bulletin',
    country: 'UK / World',
    isLive: true,
  },
  {
    id: 'cnn-international',
    name: 'CNN International',
    category: 'News',
    logo: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://rivestream.live/embed/movie/157336',
    currentProgram: 'Situation Room & Live Market Report',
    country: 'US / International',
    isLive: true,
  },
  {
    id: 'hbo-live',
    name: 'HBO Premiere Zone',
    category: 'Movies',
    logo: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidsrc.me/embed/movie?tmdb=157336',
    currentProgram: 'House of the Dragon - S2 Marathon',
    country: 'US',
    isLive: true,
  },
  {
    id: 'cine-action-hd',
    name: 'CineHD Action Movies 24/7',
    category: 'Movies',
    logo: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidlink.pro/movie/157336',
    currentProgram: 'Non-Stop Hollywood Action & Sci-Fi Blockbusters',
    country: 'Global',
    isLive: true,
  },
  {
    id: 'anime-central',
    name: 'Anime Central 24/7',
    category: 'Anime',
    logo: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidlink.pro/tv/37854/1/1',
    currentProgram: 'One Piece & Shonen Jump Classics Stream',
    country: 'JP / Global',
    isLive: true,
  },
  {
    id: 'kdrama-live',
    name: 'K-Drama Channel HD',
    category: 'Entertainment',
    logo: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidsrc.me/embed/tv?tmdb=93405&season=1&episode=1',
    currentProgram: 'Korean Hit Serials & Romance Specials',
    country: 'KR / Asia',
    isLive: true,
  },
  {
    id: 'cartoon-network',
    name: 'Kids Toon HD',
    category: 'Kids',
    logo: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=200&auto=format&fit=crop&q=80',
    streamUrl: 'https://vidsrc.to/embed/movie/550988',
    currentProgram: '24/7 Animated Movies & Cartoon Series',
    country: 'US',
    isLive: true,
  }
];
